### PR TITLE
Correct Authorisation URL

### PR DESCRIPTION
**Pull request by vwillcox**
Spotify API now needs the trailing / at the end of the authorisation URL.

Added in and now works a charm!

### CODE REVIEW

**Comment by jonashcroft** [comment]
Hi!

Thanks for raising this. Is this documented anywhere? I've just added a test app on the dashboard and can add a URL without a trailing slash (granted I haven't tried this with an auth flow yet)

Screenshot 2022-03-27 at 14 16 35

**Comment by vwillcox** [comment]
Hi, this is part of the authorization flow.
If you do not amend the two places you have the return URL in the code, you get an error on pressing the button, and again once authorized you do not get returned to the now playing screen.

Happy to do a screen recording later of the issues.

**Comment by jonashcroft** [comment]
Okay, cool! Thanks again. I'm actually away on vacation for a few days but will get this merged in this weekend.

**Comment by jonashcroft** [comment]
Hey! 

Sorry for the late replies on this, I've just got round to recreating this in my local environment. I had issues recreating this when testing a version on Netlify in a few different browser sessions. 

From what I can tell the root-cause of this issue occurs when the Redirect URI in the Spotify dashboard have a trailing slash in, but your live URL doesn't.

For example:

This throws _Invalid URI_ error:
Screenshot 2022-04-06 at 22 12 51

This allows for a valid login:
Screenshot 2022-04-06 at 22 14 06

I'm hesitant to hardcode/force a trailing slash in the codebase because we might end up with future scenarios where issues are raised for the reverse scenario.

Happy to do some further testing and see another recreation.

**Comment by jonashcroft** [comment]
Closing this PR.

It looks like the Spotify dashboard will automatically add a trailing slash to the Redirect URI, whereas Netlify does not have trailing slashes.

[README has been updated](https://github.com/jonashcroft/Nowify/commit/fc7df9f4708c35048bae7f78a25706e44efe6a4b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R58).

**Pull request closed without merging**
